### ISSUE TITLE
🚀 Publish `1.0.0`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-constructor-spy#41]
## Overview

* Publish version as `1.0.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #42
- [x] Publish.
- [x] #44
- [x] Push version tag `1.0.0` on main

## npm login to GitHub Packages before publishing

- [x] get login password from your GitHub settings
Go to → https://github.com/settings/tokens
- [x] copy your `personal access token` created
- [x] run in terminal
    ```
    % npm login --registry=https://npm.pkg.github.com/

    Username: your-github-account-in-lower-case-only
    Password:
    Email: your.mail.account@gmail.com
    Logged in as [your-name] on https://npm.pkg.github.com/.
    ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `40b442b`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/jest-constructor-spy@1.0.0
  npm notice === Tarball Contents === 
  npm notice 1.1kB LICENSE              
  npm notice 1.5kB README.md            
  npm notice 109B  index.js             
  npm notice 1.2kB lib/ConstructorSpy.js
  npm notice 1.2kB package.json         
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/jest-constructor-spy          
  npm notice version:       1.0.0                                        
  npm notice filename:      @openreachtech/jest-constructor-spy-1.0.0.tgz
  npm notice package size:  2.3 kB                                       
  npm notice unpacked size: 5.0 kB                                       
  npm notice shasum:        071013452fd8e8d05055a3b905f14baa7559e9d0     
  npm notice integrity:     sha512-mmKWl3MO63lPz[...]nBVbk5DJO/b2g==     
  npm notice total files:   5                                            
  npm notice 
  + @openreachtech/jest-constructor-spy@1.0.0
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [x] `npm publish`
