### ISSUE TITLE
🚀 Publish `1.0.1`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-constructor-spy#51]
## Overview

* Publish version as `1.0.1`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #52
- [x] Publish.
- [x] #58
- [x] Push version tag `1.0.1` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `eaa340b`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/jest-constructor-spy@1.0.1
  npm notice === Tarball Contents === 
  npm notice 1.1kB LICENSE                
  npm notice 2.2kB README.md              
  npm notice 134B  config/setupAfterEnv.js
  npm notice 109B  index.js               
  npm notice 1.2kB lib/ConstructorSpy.js  
  npm notice 1.1kB package.json           
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/jest-constructor-spy          
  npm notice version:       1.0.1                                        
  npm notice filename:      @openreachtech/jest-constructor-spy-1.0.1.tgz
  npm notice package size:  2.5 kB                                       
  npm notice unpacked size: 5.8 kB                                       
  npm notice shasum:        69f1f44ac0065ac08a032b8ef495a69453654e82     
  npm notice integrity:     sha512-JW7S+ZtlU5W2Z[...]l6DiDedzFYrDw==     
  npm notice total files:   6                                            
  npm notice 
  + @openreachtech/jest-constructor-spy@1.0.1
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [x] `npm publish`
