### ISSUE TITLE
💪 Replace `lib/environment/setupAfterEnv.js` to `config/`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-constructor-spy#54]
## Overview

* Replace `lib/environment/setupAfterEnv.js` to `config/`

## Tasks

- [x] Replace `lib/environment/setupAfterEnv.js` to `config/`
- [x] Update `jest.config.js`
- [x] Update `files` of `package.json`
