### ISSUE TITLE
🚀 Publish `1.0.2`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-constructor-spy#66]
## Overview

* Publish version as `1.0.2`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #68
- [x] Publish by procedure
- [x] #73
- [x] Push version tag `1.0.2` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `e352075`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [ ] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/jest-constructor-spy@1.0.2
  npm notice === Tarball Contents === 
  npm notice 1.1kB LICENSE                
  npm notice 2.8kB README.md              
  npm notice 134B  config/setupAfterEnv.js
  npm notice 109B  index.js               
  npm notice 1.5kB lib/ConstructorSpy.js  
  npm notice 1.1kB package.json           
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/jest-constructor-spy          
  npm notice version:       1.0.2                                        
  npm notice filename:      @openreachtech/jest-constructor-spy-1.0.2.tgz
  npm notice package size:  2.9 kB                                       
  npm notice unpacked size: 6.7 kB                                       
  npm notice shasum:        06dcb712ed8c5141aac94b98a6871b37b7c1755f     
  npm notice integrity:     sha512-O/fRkr+AFcOUQ[...]xu/7V5rLezIDA==     
  npm notice total files:   6                                            
  npm notice 
  npm notice Publishing to https://npm.pkg.github.com (dry-run)
  + @openreachtech/jest-constructor-spy@1.0.2
  ```

- [x] Check log of `--dry-run` by other member before actual publishing
  - target commit as: `e352075`
  - node version: `v18.20.1`
  - npm version: `8.19.4`

- [x] Publish

  ```console
  git status
  git diff e352075
  ```

  ```console
  npm publish --access public
  ```
