### ISSUE TITLE
⚙️ Update `test.yml` of GitHub Workflows

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-constructor-spy#72]
## Overview

* Update `test.yml` of GitHub Workflows

## Tasks

- [x] ⚙️ Tidy up while the code with empty lines
- [x] ⚙️ Add `name` to each step in `jobs:`
- [x] ⚙️ Update Node.js version to `[20.x]`
