### ISSUE TITLE
⚙️ Setup dual package

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-constructor-spy#87]
## Overview

* Setup dual package

## Tasks

- [x] Add `index.mjs`
- [x] Add `exports` field in `package.json`
- [x] Tidy up `files` field in `package.json`
- [x] ~Add `index.mjs` to `ignores` field in `eslint.config.js`~
