### ISSUE TITLE
🚀 Publish `1.1.0`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-constructor-spy#91]
## Overview

* Publish version as `1.1.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #92
- [x] Publish by procedure
- [x] #98
- [x] Push version tag `1.1.0` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `befb15c`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run 
  npm notice 
  npm notice 📦  @openreachtech/jest-constructor-spy@1.1.0
  npm notice === Tarball Contents === 
  npm notice 1.1kB LICENSE                 
  npm notice 2.8kB README.md               
  npm notice 134B  config/setupAfterEnv.js 
  npm notice 207B  config/setupAfterEnv.mjs
  npm notice 109B  index.js                
  npm notice 176B  index.mjs               
  npm notice 1.5kB lib/ConstructorSpy.js   
  npm notice 1.3kB package.json            
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/jest-constructor-spy         
  npm notice version:       1.1.0                                       
  npm notice filename:      openreachtech-jest-constructor-spy-1.1.0.tgz
  npm notice package size:  3.0 kB                                      
  npm notice unpacked size: 7.3 kB                                      
  npm notice shasum:        9d1774a57934f997dec12f036a1e4ace1d369093    
  npm notice integrity:     sha512-rrUAt8p2GSg2T[...]trAvnRmFaf8/w==    
  npm notice total files:   8                                           
  npm notice 
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @openreachtech/jest-constructor-spy@1.1.0
  ```

- [x] Check log of `--dry-run` by other member before actual publishing
  - target commit as: `befb15c`
  - node version: `v20.14.0`
  - npm version: `10.5.2`

- [x] Publish

  ```console
  git status
  git diff befb15c
  ```

  ```console
  npm publish --access public
  ```
