### ISSUE TITLE
⚒ Add `config/setupAfterEnv.mjs`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-constructor-spy#94]
## Overview

* Implement `config/setupAfterEnv.mjs`

## Tasks

- [x] ⚒ Add `config/setupAfterEnv.mjs`
- [x] ~⚙️ Update `files` field in `package.json to add `config/setupAfterEnv.mjs`~ (not require)
- [x] ⚙️ Update `ignores` field in `eslint.config.js` to add `config/setupAfterEnv.mjs`
